# Generated by Django 6.0.7 on 2026-07-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfig',
            name='allowed_models',
            field=models.JSONField(blank=True, default=list, help_text='Whitelisted Django models allowed for this agent (e.g. ["store.Product", "store.Order"]). Leave empty to inherit all models configured in settings.py.'),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='blocked_fields',
            field=models.JSONField(blank=True, default=list, help_text='Field names or substrings blocked for this agent (e.g. ["password", "is_superuser"]). Leave empty to inherit global default blocked fields.'),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='extra_approval_tools',
            field=models.JSONField(blank=True, default=list, help_text='Extra tool names (beyond add_record and update_record) that require explicit user approval before execution. e.g. ["send_email", "send_push_notification"]'),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='extra_tools',
            field=models.JSONField(blank=True, default=list, help_text='Names of ADDITIONAL registered tools to add on top of the built-in ORM tools. Built-in tools (get_model_schema, query_records, add_record, update_record) are always included automatically. Add custom tools here: e.g. ["send_email", "send_push_notification"]. Each name must be registered with @register_tool in your code.'),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive agents reject API requests with 404.'),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='max_tokens',
            field=models.IntegerField(blank=True, help_text="Max response tokens. Leave blank to use DJANGO_AI_AGENT['MAX_TOKENS'].", null=True),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='model_name',
            field=models.CharField(blank=True, help_text="OpenRouter model ID to use (e.g. 'google/gemini-2.5-flash'). Leave blank to use DJANGO_AI_AGENT['DEFAULT_MODEL'].", max_length=200),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='name',
            field=models.SlugField(help_text="Unique slug for this agent (e.g. 'support', 'admin-bot'). Used in API URLs: POST /agent/chat/?agent=support", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='summary_threshold',
            field=models.IntegerField(blank=True, help_text="Number of messages before conversation is summarized. Leave blank to use DJANGO_AI_AGENT['SUMMARY_THRESHOLD'].", null=True),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='system_prompt',
            field=models.TextField(help_text="The agent's personality and instructions. Supports {user_id}, {date}, {summary} placeholders — see docs."),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_user',
            field=models.BooleanField(help_text='True if sent by human user, False if generated by AI.'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='model_name',
            field=models.CharField(blank=True, default='', help_text='OpenRouter model name used for generation (if AI message).', max_length=200),
        ),
    ]
