# Generated by Django 6.0.7 on 2026-09-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_langgraph_agent', '0002_alter_agentconfig_allowed_models_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfig',
            name='extra_tools',
            field=models.JSONField(blank=True, default=list, help_text='Names of ADDITIONAL registered tools to add on top of the built-in ORM tools. Built-in tools (get_model_schema, query_records, aggregate_model_records, add_record, update_record) are always included automatically. Add custom tools here: e.g. ["send_email", "send_push_notification"]. Each name must be registered with @register_tool in your code.'),
        ),
    ]
